sonar.projectKey=SIGA
sonar.host.url=https://sonarqube.inf.uct.cl
sonar.token=sqp_322cfe132bb83e7f61352376a27c08a243cee8bb
sonar.sources=backend/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.exclusions=**/node_modules/**, **/*.test.js, **/jest.config.js, **/vite.config.js, **/coverage/**, backend/src/generated/**, backend/src/docs/**, frontend/siga/src/**
sonar.coverage.exclusions=backend/src/generated/**, backend/src/docs/**, backend/src/config/**, backend/src/index.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info