sonar.projectKey=SIGA
sonar.javascript.lcov.reportPaths=backend/coverage/lcov-report/dto/lcov.info
sonar.host.url=https://sonarqube.inf.uct.cl
sonar.sources=backend/src,frontend/siga/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**, **/*.test.js, **/jest.config.js, **/vite.config.js, **/coverage/**